### ISSUE TITLE
Canary checker crashed with a panic

### ISSUE THREAD

**Issue by adityathebe** [flanksource/canary-checker#1468]
```
panic: interface conversion: interface {} is time.Duration, not map[string]interface {}

goroutine 12247 [running]:
github.com/flanksource/canary-checker/api/context.(*Context).GetContextualFunctions(0xc014bc4000)
        /home/gunners/Projects/flanksource/canary-checker/api/context/functions.go:13 +0x22b
github.com/flanksource/canary-checker/checks.template(0xc014bc4000, {{0x0, 0x0}, {0x0, 0x0}, {0xc0143d7f24, 0xb}, {0x0, 0x0}})
        /home/gunners/Projects/flanksource/canary-checker/checks/common.go:69 +0x128
github.com/flanksource/canary-checker/checks.processTemplates(0xc014bc4000, 0xc016845100)
        /home/gunners/Projects/flanksource/canary-checker/checks/runchecks.go:232 +0x5d3
github.com/flanksource/canary-checker/checks.TransformResults(0xc013e50600, {0xc01423ed20, 0x2, 0x2})
        /home/gunners/Projects/flanksource/canary-checker/checks/runchecks.go:172 +0x3cf
github.com/flanksource/canary-checker/checks.RunChecks(0xc013e50600)
        /home/gunners/Projects/flanksource/canary-checker/checks/runchecks.go:100 +0x99b
github.com/flanksource/canary-checker/pkg/jobs/canary.CanaryJob.Run({{{{0x0, 0x0}, {0x0, 0x0}}, {{0xc014154580, 0x9}, {0x0, 0x0}, {0xc0141545c8, 0x8}, ...}, ...}, ...}, ...)
        /home/gunners/Projects/flanksource/canary-checker/pkg/jobs/canary/canary_jobs.go:109 +0xb05
github.com/flanksource/duty/job.Job.Run({{{{0xae82b80, 0xc0143e3650}, {0xae99f40, 0xc013e8a680}, 0xa70bb68, 0xa70bb70, {0xae1b8c0, 0xc01413e140}}}, {0xa44d256, 0xd}, ...})
        /home/gunners/Projects/flanksource/duty/job/job.go:71 +0x675
github.com/robfig/cron/v3.(*Cron).startJob.func1()
        /home/gunners/.local/share/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x9d
created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 42
        /home/gunners/.local/share/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xc6
```

This is on my local instance

**Comment by adityathebe** [comment]
This was fixed on gomplate
